---
title: "riskmetric_scores"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{riskmetric_scores}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(riskreports)
library("riskmetric")
```

We need to have the source files uncompressed:

```{r}
# dplyr_pkg_ref <- pkg_ref("inst/source/dplyr_1.1.4.tar.gz")
# riskmetric_pkg_ref <- pkg_ref("inst/source/riskmetric_0.2.4.tar.gz")

# This needs to be on its own folder dplyr/dplyr/DESCRIPTION so if used with untar, keep add the basename there.
dplyr_pkg_ref <- riskmetric::pkg_ref("dplyr", lib.loc = "inst/source/dplyr")
riskmetric_pkg_ref <- riskmetric::pkg_ref("riskmetric", lib.loc = "inst/source/riskmetric")
```

We generate the assessment with riskmetric:

```{r}
riskmetric_assessment <- riskmetric::pkg_assess(riskmetric_pkg_ref)
dplyr_assessment <- riskmetric::pkg_assess(dplyr_pkg_ref)
```

Then we can start working on the assessment. 
This is not a quantification of a risk like `riskmetric::pkg_score()` but some minor conversion to a value of length 1, one character or one numeric value. 

```{r}
riskmetric_a <- assessment(riskmetric_assessment)
dplyr_a <- assessment(dplyr_assessment)

dplyr_a
riskmetric_a
```


This is different from the scores, such as the ones [previously used](https://github.com/pharmaR/repos/blob/main/ubuntu-22.04/4.4/riskscore/src/contrib/PACKAGES).

```{r}
download.file("https://raw.githubusercontent.com/pharmaR/repos/refs/heads/main/ubuntu-22.04/4.4/riskscore/src/contrib/PACKAGES?token=GHSAT0AAAAAACZC3CYXK3Q62EBLVXQH5CHSZZ7I2BA",
              destfile = "inst/source/UBUNTU-PACKAGES")
```


