---
title: "Generate Customized Report"
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(riskreports)
```

## Standard R Validation Report

```{r eval=FALSE}

library(riskreports)
# Specify the folder where the files should go (here for easy access on the website)
options("riskreports_output_dir" = "C:/Users/XXXX/GitProjects/TMP_tests")

pr <- package_report(
  template_path = system.file("report/package", package = "riskreports"),
  package_name = "dplyr",
  package_version = "1.1.4",
  params = list(
    assessment_path = system.file("assessments/dplyr.rds", package = "riskreports")),
  quiet = FALSE # To silence quarto output for readability
)
pr
```

## A Customized Report for a Package

- Include customized log in input parameters `logo_path` and `logo_path_dark`.
- Other customized css can be included by modify the css files in the template path.

```{r eval=FALSE}
library(riskreports)
# Specify the folder where the files should go (here for easy access on the website)
options("riskreports_output_dir" = "C:/Users/XXXXX/GitProjects/TMP_tests")

# Example usage
 pr <- package_report(
   template_path = "C:/Users/XXXXX/GitProjects/riskreports/inst/report/package",
   package_name = "dplyr",
   package_version = "1.1.4",
   params = list(
     assessment_path = system.file("assessments/dplyr.rds", package = "riskreports"),
     image = "rhub/ref-image"
   ),
   logo_path = "C:/Users/XXXXX/GitProjects/TMP_tests/logo.png",
   logo_path_dark = "C:/Users/XXXXX/GitProjects/TMP_tests/logo_dark.png"
 )
 pr
#' file.remove(pr)
```